using System;
using System.Data.Common;
using System.IO;
using AwesomeAssertions;
using Xunit;

namespace EFCore.Scaffolding.Tests;

public class ScaffolderSettingsTest
{
    [Theory]
    [InlineData("<auto-generated>", true)]
    [InlineData("anything else", false)]
    public void ScaffolderSettings_DefaultShouldDeleteFile(string contents, bool shouldDelete)
    {
        var file = new FileInfo(Guid.NewGuid().ToString());
        try
        {
            File.WriteAllText(file.FullName, contents);
            ScaffolderSettings.DefaultShouldDeleteFile(file).Should().Be(shouldDelete);
        }
        finally
        {
            file.Delete();
        }
    }

    [Fact]
    public void ScaffolderSettings_DefaultGetDisplayableConnectionString()
    {
        var builder = new DbConnectionStringBuilder { ConnectionString = "Host=localhost;User=admin;Password=letmein" };
        var connectionString = ScaffolderSettings.DefaultGetDisplayableConnectionString(builder);
        connectionString.Should().Be("host=localhost;user=admin");
    }
}