// <auto-generated>
//
// ┌───────────────────┬──────────────────────────────────────┐
// │ Provider          │ Microsoft.EntityFrameworkCore.Sqlite │
// ├───────────────────┼──────────────────────────────────────┤
// │ Connection String │ Data Source=Chinook.sqlite           │
// └───────────────────┴──────────────────────────────────────┘
// 
// </auto-generated>

#nullable enable
#pragma warning disable

using System;
using System.Collections.Generic;

namespace ScaffoldOneTableOrderedColumns;

public partial class Customer
{
    public string? Address { get; set; }

    public string? City { get; set; }

    public string? Company { get; set; }

    public string? Country { get; set; }

    public long CustomerId { get; set; }

    public string Email { get; set; } = null!;

    public string FirstName { get; set; } = null!;

    public string LastName { get; set; } = null!;

    public string? Phone { get; set; }

    public string? PostalCode { get; set; }

    public string? State { get; set; }

    public long? SupportRepId { get; set; }
}
