using System;
using System.Data.Common;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using EFCore.Scaffolding.Extensions;
using Microsoft.Data.SqlClient;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.EntityFrameworkCore.Design.Internal;
using Microsoft.EntityFrameworkCore.Scaffolding;
using Microsoft.Extensions.DependencyInjection;
using MySqlConnector;
using Npgsql;
using Oracle.ManagedDataAccess.Client;

namespace EFCore.Scaffolding;

/// <summary>
/// Creates an EntityFramework Core DbContext class and associated entities from an existing database.
/// </summary>
public static class Scaffolder
{
    private class DesignTimeServices : IDesignTimeServices
    {
        [ThreadStatic]
        public static Settings? CurrentSettings;

        public void ConfigureDesignTimeServices(IServiceCollection serviceCollection)
        {
            if (CurrentSettings == null)
                throw new InvalidOperationException("The current settings must not be null");

            serviceCollection.AddSingleton(CurrentSettings);
            serviceCollection.AddFiltering();
            serviceCollection.AddRenaming();
            serviceCollection.AddWorkarounds();

            CurrentSettings = null;
        }
    }

    public static SavedModelFiles Run(Settings settings)
    {
        DeleteExistingFiles(settings);
        var savedModelFiles = ScaffoldContextAndEntities(settings);
        AddAutogeneratedComment(settings, savedModelFiles);
        return savedModelFiles;
    }

    private static void DeleteExistingFiles(Settings settings)
    {
        if (!settings.OutputDirectory.Exists)
        {
            return;
        }

        foreach (var file in settings.OutputDirectory.GetFiles("*.cs").Where(settings.ShouldDeleteFile))
        {
            file.Delete();
        }
    }

    private static SavedModelFiles ScaffoldContextAndEntities(Settings settings)
    {
        var designAssembly = typeof(DesignTimeServices).Assembly;

        var operations = new DatabaseOperations(
            new OperationReporter(settings.ReportHandler),
            assembly: designAssembly,
            startupAssembly: designAssembly,
            projectDir: "",
            rootNamespace: "",
            language: null,
            nullable: true,
            args: Array.Empty<string>()
        );

        var modelNamespace = settings.ModelNamespace ?? settings.OutputDirectory.Name;
        var contextNamespace = settings.ContextOutputDirectory == null ? modelNamespace : settings.ContextNamespace ?? settings.ContextOutputDirectory.Name;

        DesignTimeServices.CurrentSettings = settings;
        return operations.ScaffoldContext(
            provider: GetProviderName(settings.ConnectionStringBuilder),
            connectionString: settings.ConnectionStringBuilder.ConnectionString,
            outputDir: settings.OutputDirectory.FullName,
            outputContextDir: (settings.ContextOutputDirectory ?? settings.OutputDirectory).FullName,
            dbContextClassName: settings.ContextName,
            schemas: settings.Schemas,
            tables: settings.Tables,
            modelNamespace: modelNamespace,
            contextNamespace: contextNamespace,
            useDataAnnotations: false,
            overwriteFiles: false,
            useDatabaseNames: false,
            suppressOnConfiguring: true,
            noPluralize: false
        );
    }

    private static string GetProviderName(DbConnectionStringBuilder connectionStringBuilder)
    {
        using var dbContext = CreateDbContext(connectionStringBuilder);
        return dbContext.Database.ProviderName ?? throw new InvalidOperationException($"Provider name for {connectionStringBuilder.GetType().Name} could not be determined.");
    }

    private static DbContext CreateDbContext(DbConnectionStringBuilder connectionStringBuilder)
    {
        var connectionStringBuilderName = connectionStringBuilder.GetType().Name;
        var builder = new DbContextOptionsBuilder();
        _ = connectionStringBuilder switch
        {
            MySqlConnectionStringBuilder => builder.UseMySql(MySqlServerVersion.LatestSupportedServerVersion),
            NpgsqlConnectionStringBuilder => builder.UseNpgsql(),
            OracleConnectionStringBuilder => builder.UseOracle(),
            SqliteConnectionStringBuilder => builder.UseSqlite(),
            SqlConnectionStringBuilder => builder.UseSqlServer(),
            _ => throw new NotSupportedException($"Unsupported connection string builder: {connectionStringBuilderName}. " +
                                                 "The supported connection string builders are " +
                                                 $"{nameof(MySqlConnectionStringBuilder)}, " +
                                                 $"{nameof(NpgsqlConnectionStringBuilder)}, " +
                                                 $"{nameof(OracleConnectionStringBuilder)}, " +
                                                 $"{nameof(SqliteConnectionStringBuilder)} and {nameof(SqlConnectionStringBuilder)}.")
        };
        return new DbContext(builder.Options);
    }

    private static DbConnectionStringBuilder Copy(DbConnectionStringBuilder connectionStringBuilder)
    {
        using var dbContext = CreateDbContext(connectionStringBuilder);
        using var connection = dbContext.Database.GetDbConnection();
        var factory = DbProviderFactories.GetFactory(connection)
                      ?? throw new InvalidOperationException($"DbProviderFactories.GetFactory({connection}) returned null.");
        var builder = factory.CreateConnectionStringBuilder()
                      ?? throw new InvalidOperationException($"CreateConnectionStringBuilder() returned null for {factory}.");
        builder.ConnectionString = connectionStringBuilder.ConnectionString;
        return builder;
    }

    private static void AddAutogeneratedComment(Settings settings, SavedModelFiles savedModelFiles)
    {
        Parallel.ForEach(savedModelFiles.AdditionalFiles.Append(savedModelFiles.ContextFile).Distinct(), filePath =>
        {
            var lines = new StringBuilder();
            lines.AppendLine("// <auto-generated>");
            lines.AppendLine("//");
            lines.AppendLine($"// Generated from {settings.GetDisplayableConnectionString(Copy(settings.ConnectionStringBuilder))}");
            lines.AppendLine("// ");
            lines.AppendLine("// </auto-generated>");
            lines.AppendLine();
            lines.AppendLine("#nullable enable");
            lines.AppendLine("#pragma warning disable");
            lines.AppendLine();
            foreach (var line in File.ReadAllLines(filePath))
            {
                lines.AppendLine(line);
            }
            File.WriteAllText(filePath, lines.ToString());
        });
    }
}